version: "3"
 
services:


 elk:
   image: myelastic
   ports:
     - "5601:5601"
     - "9200:9200"
     - "9300:9300"
     - "5044:5044"
 
 nifi:
   image: apache/nifi
   ports:
     - "8080:8080"
   volumes:
     - C:\Users\.docker\nifi:/input
